export type LeadStatus = 'Novo' | 'Qualificado' | 'Orçamento' | 'Negociação' | 'Fechado';
export type Urgency = 'Baixa' | 'Média' | 'Alta';

export interface Lead {
  id: string;
  nome: string;
  telefone: string;
  email: string;
  servico: string;
  origem: string;
  status: LeadStatus;
  urgencia: Urgency;
  valorPotencial: number;
  data: string;
  observacoes: string;
}

export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    nome: 'João Pereira',
    telefone: '(11) 98888-1111',
    email: 'joao.pereira@email.com',
    servico: 'Instalação de Ar-condicionado',
    origem: 'Instagram',
    status: 'Novo',
    urgencia: 'Média',
    valorPotencial: 850,
    data: '2026-08-30',
    observacoes: 'Interesse em 2 máquinas de 9000 BTUs.',
  },
  {
    id: '2',
    nome: 'Mariana Costa',
    telefone: '(21) 97777-2222',
    email: 'mariana.costa@email.com',
    servico: 'Projeto Elétrico',
    origem: 'Google',
    status: 'Qualificado',
    urgencia: 'Alta',
    valorPotencial: 2400,
    data: '2026-08-29',
    observacoes: 'Reforma residencial completa.',
  },
  {
    id: '3',
    nome: 'Ricardo Alves',
    telefone: '(31) 96666-3333',
    email: 'ricardo.alves@email.com',
    servico: 'Manutenção de Ar-condicionado',
    origem: 'Site',
    status: 'Negociação',
    urgencia: 'Baixa',
    valorPotencial: 1200,
    data: '2026-08-28',
    observacoes: 'Higienização de 4 aparelhos.',
  },
  {
    id: '4',
    nome: 'Fernanda Lima',
    telefone: '(41) 95555-4444',
    email: 'fernanda.lima@email.com',
    servico: 'Câmeras de Segurança',
    origem: 'Instagram',
    status: 'Orçamento',
    urgencia: 'Média',
    valorPotencial: 3500,
    data: '2026-08-27',
    observacoes: 'Instalação em condomínio.',
  },
  {
    id: '5',
    nome: 'Carlos Eduardo',
    telefone: '(51) 94444-5555',
    email: 'carlos.edu@email.com',
    servico: 'Automação Residencial',
    origem: 'Indicação',
    status: 'Fechado',
    urgencia: 'Alta',
    valorPotencial: 7000,
    data: '2026-08-26',
    observacoes: 'Iluminação e som ambiente.',
  },
  {
    id: '6',
    nome: 'Ana Beatriz',
    telefone: '(61) 93333-6666',
    email: 'ana.beatriz@email.com',
    servico: 'Instalação de Ar-condicionado',
    origem: 'Google',
    status: 'Novo',
    urgencia: 'Baixa',
    valorPotencial: 900,
    data: '2026-08-25',
    observacoes: 'Apenas 1 máquina.',
  },
  {
    id: '7',
    nome: 'Roberto Souza',
    telefone: '(71) 92222-7777',
    email: 'roberto.souza@email.com',
    servico: 'Instalações Elétricas',
    origem: 'Site',
    status: 'Qualificado',
    urgencia: 'Média',
    valorPotencial: 1800,
    data: '2026-08-24',
    observacoes: 'Troca de fiação antiga.',
  },
  {
    id: '8',
    nome: 'Juliana Mendes',
    telefone: '(81) 91111-8888',
    email: 'juliana.mendes@email.com',
    servico: 'Segurança Eletrônica',
    origem: 'Instagram',
    status: 'Orçamento',
    urgencia: 'Alta',
    valorPotencial: 4200,
    data: '2026-08-23',
    observacoes: 'Alarme e sensores de presença.',
  },
  {
    id: '9',
    nome: 'Marcelo Dias',
    telefone: '(11) 90000-9999',
    email: 'marcelo.dias@email.com',
    servico: 'Manutenção de Ar-condicionado',
    origem: 'Google',
    status: 'Negociação',
    urgencia: 'Média',
    valorPotencial: 600,
    data: '2026-08-22',
    observacoes: 'Carga de gás.',
  },
  {
    id: '10',
    nome: 'Patrícia Gomes',
    telefone: '(21) 99999-0000',
    email: 'patricia.gomes@email.com',
    servico: 'Automação Residencial',
    origem: 'Site',
    status: 'Fechado',
    urgencia: 'Baixa',
    valorPotencial: 12000,
    data: '2026-08-21',
    observacoes: 'Sistema completo de smart home.',
  },
  {
    id: '11',
    nome: 'Lucas Martins',
    telefone: '(31) 98765-4321',
    email: 'lucas.martins@email.com',
    servico: 'Instalações Elétricas',
    origem: 'Indicação',
    status: 'Novo',
    urgencia: 'Alta',
    valorPotencial: 1500,
    data: '2026-08-20',
    observacoes: 'Curto circuito no quadro.',
  },
  {
    id: '12',
    nome: 'Carla Silva',
    telefone: '(41) 98765-1234',
    email: 'carla.silva@email.com',
    servico: 'Câmeras de Segurança',
    origem: 'Instagram',
    status: 'Qualificado',
    urgencia: 'Média',
    valorPotencial: 2100,
    data: '2026-08-19',
    observacoes: 'Instalação de 4 câmeras IP.',
  },
  {
    id: '13',
    nome: 'André Santos',
    telefone: '(51) 98765-5678',
    email: 'andre.santos@email.com',
    servico: 'Instalação de Ar-condicionado',
    origem: 'Google',
    status: 'Orçamento',
    urgencia: 'Baixa',
    valorPotencial: 1100,
    data: '2026-08-18',
    observacoes: 'Ar split 12000 BTUs.',
  },
    {
    id: '14',
    nome: 'Beatriz Rocha',
    telefone: '(61) 98765-9876',
    email: 'beatriz.rocha@email.com',
    servico: 'Segurança Eletrônica',
    origem: 'Site',
    status: 'Negociação',
    urgencia: 'Alta',
    valorPotencial: 5000,
    data: '2026-08-17',
    observacoes: 'Interfonia e controle de acesso.',
  },
  {
    id: '15',
    nome: 'Diego Oliveira',
    telefone: '(71) 98765-1111',
    email: 'diego.oliveira@email.com',
    servico: 'Automação Residencial',
    origem: 'Indicação',
    status: 'Fechado',
    urgencia: 'Média',
    valorPotencial: 3000,
    data: '2026-08-16',
    observacoes: 'Configuração de Alexa e luzes.',
  },
];
