import { OrganizationConfig } from '@/lib/types/config';

export const iluminarConfig: OrganizationConfig = {
  id: 'org_iluminar_001',
  slug: 'iluminar',
  name: 'Iluminar',
  branding: {
    primaryColor: '#1565d8',
    secondaryColor: '#f5c518',
  },
  publicContact: {
    whatsapp: '5545988429228',
    websiteUrl: 'https://iluminarcvel.com.br',
    websiteLabel: 'Voltar ao site da Iluminar',
  },
  services: [
    { id: 'eletr', label: 'Elétrica', icon: '⚡' },
    { id: 'ar', label: 'Ar-condicionado', icon: '❄️' },
    { id: 'seg', label: 'Segurança eletrônica', icon: '🛡️' },
    { id: 'auto', label: 'Automação residencial', icon: '🏠' },
  ],
  forms: [
    {
      id: 'form_iluminar_orcamento',
      slug: 'iluminar-orcamento',
      steps: [
        {
          id: 'details',
          title: 'Conte rapidamente o problema',
          subtitle: 'Só precisamos de algumas informações para entender como ajudar.',
          fields: [
            {
              id: 'problem',
              type: 'select',
              label: 'O que você precisa resolver?',
              required: true,
              options: [
                { label: 'Tomada ou interruptor', value: 'Tomada ou interruptor' },
                { label: 'Iluminação', value: 'Iluminação' },
                { label: 'Chuveiro', value: 'Chuveiro' },
                { label: 'Disjuntor ou quadro elétrico', value: 'Disjuntor ou quadro elétrico' },
                { label: 'Falta de energia em algum ponto', value: 'Falta de energia em algum ponto' },
                { label: 'Ventilador', value: 'Ventilador' },
                { label: 'Padrão de energia / Copel', value: 'Padrão de energia / Copel' },
                { label: 'Outro', value: 'Outro' },
              ],
              order: 1,
              showWhen: { field: 'serviceId', equals: 'eletr' },
            },
            {
              id: 'problem',
              type: 'select',
              label: 'O que você precisa resolver?',
              required: true,
              options: [
                { label: 'Quero instalar', value: 'Quero instalar' },
                { label: 'Não está gelando', value: 'Não está gelando' },
                { label: 'Está vazando água', value: 'Está vazando água' },
                { label: 'Está fazendo barulho', value: 'Está fazendo barulho' },
                { label: 'Quero higienizar', value: 'Quero higienizar' },
                { label: 'Quero retirar ou mudar de lugar', value: 'Quero retirar ou mudar de lugar' },
                { label: 'Quero comprar um aparelho', value: 'Quero comprar um aparelho' },
                { label: 'Outro', value: 'Outro' },
              ],
              order: 2,
              showWhen: { field: 'serviceId', equals: 'ar' },
            },
            {
              id: 'problem',
              type: 'select',
              label: 'O que você precisa resolver?',
              required: true,
              options: [
                { label: 'Câmeras', value: 'Câmeras' },
                { label: 'Cerca elétrica', value: 'Cerca elétrica' },
                { label: 'Alarme', value: 'Alarme' },
                { label: 'Interfone / controle de acesso', value: 'Interfone / controle de acesso' },
                { label: 'Fechadura eletrônica', value: 'Fechadura eletrônica' },
                { label: 'Outro', value: 'Outro' },
              ],
              order: 3,
              showWhen: { field: 'serviceId', equals: 'seg' },
            },
            {
              id: 'problem',
              type: 'select',
              label: 'O que você precisa resolver?',
              required: true,
              options: [
                { label: 'Iluminação inteligente', value: 'Iluminação inteligente' },
                { label: 'Controle de equipamentos', value: 'Controle de equipamentos' },
                { label: 'Automação de ambientes', value: 'Automação de ambientes' },
                { label: 'Quero saber o que é possível automatizar', value: 'Quero saber o que é possível automatizar' },
                { label: 'Outro', value: 'Outro' },
              ],
              order: 4,
              showWhen: { field: 'serviceId', equals: 'auto' },
            },
            {
              id: 'hasEquipment',
              type: 'select',
              label: 'Você já tem o aparelho?',
              options: [
                { label: 'Sim', value: 'Sim' },
                { label: 'Não', value: 'Não' },
              ],
              order: 5,
              showWhen: { field: 'problem', equals: 'Quero instalar' },
            },
            {
              id: 'btus',
              type: 'text',
              label: 'Se souber, qual a capacidade do aparelho?',
              placeholder: 'Ex: 9.000 ou 12.000 BTUs',
              order: 6,
              showWhen: { field: 'problem', equals: 'Quero instalar' },
            },
            {
              id: 'notes',
              type: 'textarea',
              label: 'Conte em uma frase o que está acontecendo',
              placeholder: 'Ex: A tomada da cozinha parou de funcionar e está esquentando.',
              required: true,
              order: 7,
            },
            {
              id: 'urgency',
              type: 'select',
              label: 'Quando você precisa do atendimento?',
              required: true,
              options: [
                { label: 'O quanto antes', value: 'Alta' },
                { label: 'Nos próximos dias', value: 'Média' },
                { label: 'Estou apenas consultando', value: 'Baixa' },
              ],
              order: 8,
            },
          ],
        },
        {
          id: 'contact',
          title: 'Como podemos falar com você?',
          subtitle: 'Pronto. Agora só precisamos do seu contato para a Iluminar retornar.',
          fields: [
            {
              id: 'name',
              type: 'text',
              label: 'Seu nome',
              placeholder: 'Como podemos chamar você?',
              required: true,
              order: 1,
            },
            {
              id: 'whatsapp',
              type: 'tel',
              label: 'WhatsApp',
              placeholder: '(45) 99999-9999',
              required: true,
              order: 2,
            },
            {
              id: 'location',
              type: 'text',
              label: 'Cidade e bairro',
              placeholder: 'Ex: Cascavel - Centro',
              required: true,
              order: 3,
            },
          ],
        },
      ],
    },
  ],
};
